WebsiteBanHang/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using Rotativa;
using System.Web.Mvc;
using Magnum.FileSystem;

using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class QuanLyDonHangController : BaseController
    {
        QuanLyBanHang6Entities db = new QuanLyBanHang6Entities();
        // GET: QuanLyDonHang
        public ActionResult ChuaThanhToan()
        {
            var lst = db.Bills.Where(n => n.status == false).OrderBy(n => n.buy_date);
            return View(lst);
        }
        public ActionResult ChuaGiao()
        {
            var lst = db.Bills.Where(n => n.transport_status == false).OrderBy(n => n.buy_date);
            return View(lst);
        }
        public ActionResult ChuaHoanThanh()
        {
            var lst = db.Bills.Where(n => n.buy_status == false).OrderByDescending(n => n.buy_date);
            return View(lst);
        }

        public ActionResult DaGiaoDaThanhToan()
        {
            var lst = db.Bills.Where(n => n.buy_status == true && n.transport_status == true).OrderByDescending(n => n.buy_date);
            return View(lst);
        }
        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill model = db.Bills.SingleOrDefault(n => n.Id == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            // Lấy ds chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        [HttpPost]
        public ActionResult DuyetDonHang(Bill ddh)
        {
            // Lấy dữ liệu của đơn hàng đó
            Bill ddhUpdate = db.Bills.Single(n => n.Id == ddh.Id);
            //ddhUpdate.status = ddh.status;
            ddhUpdate.buy_status = ddh.buy_status;
            ddhUpdate.transport_status = ddh.transport_status;
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == ddh.Id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            
            db.SaveChanges();
            SetAlert("Duyệt đơn hàng thành công", "success");
            return View(ddhUpdate);
        }
        public ActionResult InDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill model = db.Bills.SingleOrDefault(n => n.Id == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            // Lấy ds chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        public ActionResult InDonHang1(int? id)
        {
            Bill model = db.Bills.SingleOrDefault(n => n.Id == id);
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            SetAlert("In đơn hàng thành công", "success");
            return new PartialViewAsPdf("InDonHang",model)
            {
                FileName = Server.MapPath("~/content/hoadon.pdf")
            };
        }
        [HttpGet]
        public ActionResult xacnhan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill model = db.Bills.SingleOrDefault(n => n.Id == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            // Lấy ds chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        
        [HttpPost]
        public ActionResult xacnhan(Bill ddh)
        {
            Bill model = db.Bills.SingleOrDefault(n => n.Id == ddh.Id);
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == ddh.Id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            user kh = db.users.Single(n => n.Id == model.buyer_id);
            string gmailKH = kh.email;
            GuiEmail("Xác nhận đơn hàng",gmailKH, "txcbrand1234", "chieutxcbrand", "Đơn hàng của bạn đã được đặt thành công");
            Bill ddhUpdate = db.Bills.Single(n => n.Id == ddh.Id);
            ddhUpdate.status = true;
            db.SaveChanges();
            SetAlert("Xác nhận đơn hàng thành công", "success");
            return View(ddhUpdate);

        }

        public void GuiEmail(string Title, string ToEmail, string FromEmail, string PassWord, string Content)
        {
            // goi email
            MailMessage mail = new MailMessage();
            mail.To.Add(ToEmail); // Địa chỉ nhận
            mail.From = new MailAddress(ToEmail); // Địa chửi gửi
            mail.Subject = Title;  // tiêu đề gửi
            mail.Body = Content;                 // Nội dung
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com"; // host gửi của Gmail
            smtp.Port = 587;               //port của Gmail
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new System.Net.NetworkCredential
            (FromEmail, PassWord);//Tài khoản password người gửi
            smtp.EnableSsl = true;   //kích hoạt giao tiếp an toàn SSL
            smtp.Send(mail);   //Gửi mail đi
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

WebsiteBanHang/Views/QuanLyDonHang/ChuaGiao.cshtml
@using WebsiteBanHang.Models;

@model IEnumerable<Bill>

@{
    ViewBag.Title = "ChuaGiao";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}


<br />
<h2>Đơn hàng chưa giao cho nhà vận chuyển</h2>
<br />

<br />
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
            grid.Column("Id", header: "Mã đơn hàng"),
            grid.Column("buyer_id", header: "Họ tên KH", format: p => p.buyer_id != null ? p.user.name : ""),
            grid.Column("buy_date", header: "Ngày đặt"),
            grid.Column("status", header: "Xác nhận"),
            grid.Column("transport_status", header: "Tình trạng giao hàng"),
            grid.Column("buy_status", header: "Đã hoàn thành"),
            //grid.Column(format: p => @Html.ActionLink("in đơn hàng", "InDonHang", new { id = p.Id }, new { @target = "_blank" })),
            grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.Id }))
            //grid.Column(format: p => @Html.ActionLink("xác nhận", "xacnhan", new { id = p.Id }, new { @target = "_blank" }))

        ))


@*Css cho controller*@
<style>

    .nav > li {
        background: rgba(0,0,0,.5);
        padding: 5px 10px 5px 10px;
    }

    .divTable {
        width: 100%;
        height: 20%;
        border: 1px solid #999999;
        padding: 5px 10px 5px 10px;
    }



        .divTable td {
            border: 1px solid #999999;
            padding: 5px 10px 5px 10px;
        }

            .divTable td:hover {
                background: #FE9A2E;
            }

    .gridHead {
        background-color: #5b5a53;
    }

        .gridHead > th > a {
            color: #fff;
            padding: 5px 10px 5px 10px;
        }

    .gridFooter {
        font-weight: bold;
        padding: 5px 10px 5px 10px;
    }

    .divTable a {
        color: blue;
        padding: 5px 10px 5px 10px;
    }
    /*.gridRow {
                color:#fff;
                background-color:blueviolet;
            }
            .gridAltRow {
                color:#fff;
                background-color:darkorange;
            }*/
</style>

WebsiteBanHang/Views/QuanLyDonHang/ChuaHoanThanh.cshtml
@using WebsiteBanHang.Models;

@model IEnumerable<Bill>
@{
    ViewBag.Title = "ChuaHoanThanh";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>Đơn hàng chưa hoàn thành</h2>

@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
            grid.Column("Id", header: "Mã đơn hàng"),
            grid.Column("buyer_id", header: "Họ tên KH", format: p => p.buyer_id != null ? p.user.name : ""),
            grid.Column("buy_date", header: "Ngày đặt"),
            grid.Column("status", header: "xác nhận đơn hàng"),
            grid.Column("transport_status", header: "Tình trạng giao hàng"),
            grid.Column("buy_status", header: "Đã thanh toán"),
            
            grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.Id }))
            

        ))


@*Css cho controller*@
<style>

    .nav > li {
        background: rgba(0,0,0,.5);
        padding: 5px 10px 5px 10px;
    }

    .divTable {
        width: 100%;
        height: 20%;
        border: 1px solid #999999;
        padding: 5px 10px 5px 10px;
    }



        .divTable td {
            border: 1px solid #999999;
            padding: 5px 10px 5px 10px;
        }

            .divTable td:hover {
                background: #FE9A2E;
            }

    .gridHead {
        background-color: #5b5a53;
    }

        .gridHead > th > a {
            color: #fff;
            padding: 5px 10px 5px 10px;
        }

    .gridFooter {
        font-weight: bold;
        padding: 5px 10px 5px 10px;
    }

    .divTable a {
        color: blue;
        padding: 5px 10px 5px 10px;
    }
    /*.gridRow {
                color:#fff;
                background-color:blueviolet;
            }
            .gridAltRow {
                color:#fff;
                background-color:darkorange;
            }*/
</style>

WebsiteBanHang/Views/QuanLyDonHang/ChuaThanhToan.cshtml
@using WebsiteBanHang.Models;

@model IEnumerable<Bill>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}


<br />
<h2>Danh sách đơn hàng chưa xác nhận</h2>
<br />

<br />
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
            grid.Column("Id", header: "Mã đơn hàng"),
            grid.Column("buyer_id", header: "Họ tên KH", format: p => p.buyer_id != null ? p.user.name : ""),
            grid.Column("buy_date", header: "Ngày đặt"),
            grid.Column("status", header: "Xác nhận"),
            grid.Column(format: p => @Html.ActionLink("in đơn hàng", "InDonHang", new { id = p.Id }, new { @target = "_blank" })),
            //grid.Column("discount_percent", header: "Ưu đãi"),
            //grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.Id }, new { @target = "_blank" })),
            grid.Column(format: p => @Html.ActionLink("xác nhận", "xacnhan", new { id = p.Id }, new { @target = "_blank" }))
        ))


@*Css cho controller*@
<style>

    .nav > li {
        background: rgba(0,0,0,.5);
        padding: 5px 10px 5px 10px;
    }

    .divTable {
        width: 100%;
        height: 20%;
        border: 1px solid #999999;
        padding: 5px 10px 5px 10px;
    }



        .divTable td {
            border: 1px solid #999999;
            padding: 5px 10px 5px 10px;
        }

            .divTable td:hover {
                background: #FE9A2E;
            }

    .gridHead {
        background-color: #5b5a53;
    }

        .gridHead > th > a {
            color: #fff;
            padding: 5px 10px 5px 10px;
        }

    .gridFooter {
        font-weight: bold;
        padding: 5px 10px 5px 10px;
    }

    .divTable a {
        color: blue;
        padding: 5px 10px 5px 10px;
    }
    /*.gridRow {
                color:#fff;
                background-color:blueviolet;
            }
            .gridAltRow {
                color:#fff;
                background-color:darkorange;
            }*/
</style>

WebsiteBanHang/Views/QuanLyDonHang/DaGiaoDaThanhToan.cshtml
@using WebsiteBanHang.Models;

@model IEnumerable<Bill>

@{
    ViewBag.Title = "DaGiaoDaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>Danh sách đơn hàng đã hoàn thành</h2>
<br />

<br />
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
            grid.Column("Id", header: "Mã đơn hàng"),
            grid.Column("buyer_id", header: "Họ tên KH", format: p => p.buyer_id != null ? p.user.name : ""),
            grid.Column("buy_date", header: "Ngày đặt"),
            grid.Column("transport_status", header: "Tình trạng giao hàng"),
            grid.Column("buy_status", header: "Đã thanh toán")
            //grid.Column("discount_percent", header: "Ưu đãi")


        ))
<style>

    .nav > li {
        background: rgba(0,0,0,.5);
        padding: 5px 10px 5px 10px;
    }

    .divTable {
        width: 100%;
        height: 20%;
        border: 1px solid #999999;
        padding: 5px 10px 5px 10px;
    }



        .divTable td {
            border: 1px solid #999999;
            padding: 5px 10px 5px 10px;
        }

            .divTable td:hover {
                background: #FE9A2E;
            }

    .gridHead {
        background-color: #5b5a53;
    }

        .gridHead > th > a {
            color: #fff;
            padding: 5px 10px 5px 10px;
        }

    .gridFooter {
        font-weight: bold;
        padding: 5px 10px 5px 10px;
    }

    .divTable a {
        color: blue;
        padding: 5px 10px 5px 10px;
    }
    /*.gridRow {
                color:#fff;
                background-color:blueviolet;
            }
            .gridAltRow {
                color:#fff;
                background-color:darkorange;
            }*/
</style>

WebsiteBanHang/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using WebsiteBanHang.Models;
@model Bill

@{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<h2>Thông tin đơn hàng </h2>
<br />
<br />

@using (Html.BeginForm())
{
    <div class="ChiTietDonHang table">
        @{ IEnumerable<billproduct> lstChiTietDH = (IEnumerable<billproduct>)ViewBag.ListChiTietDH;}

        <table class="table" id="table">
            @*Thông tin đơn hàng*@
            <tr>
                <td>Mã đơn hàng: <b style="color:red">@Model.Id @Html.Hidden("Id", Model.Id)</b></td>
                <td>Mã khách hàng: <b style="color:red">@Model.user.Id</b></td>
                <td>Tên khách hàng: <b style="color:red">@Model.user.name</b></td>
                <td>Ngày đặt: @Model.buy_date.Value.ToString("dd/MM/yyy")</td>
                <td>Đã xác nhận: @Html.EditorFor(model => model.status)</td>
                <td>Đã giao: @Html.EditorFor(model => model.transport_status)</td>
                <td>Đã thanh toán: @Html.EditorFor(model => model.buy_status)</td>
            </tr>
            @*Phần chi tiết đơn hàng*@
            <tr>
                <td></td>
                <td><b>Sản phẩm</b></td>
                <td><b>Hình ảnh</b></td>
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>
            @{
                int i = 1;
            }
            @foreach (var item in lstChiTietDH)
            {

                <tr>
                    <td>@i</td>
                    <td>@item.product.name</td>
                    <td><img width="120" height="120" src="@Url.Content("~/Content/HinhAnhSP/" + @item.product.image1)" /></td>
                    <td>@item.quantity</td>
                    <td>@item.unit_price</td>
                </tr>
                { i++; }
            }


            <tr id="tt">
                <td>Tổng số lượng: @Model.billproducts.Sum(n => n.quantity)</td>
                <td>Tổng tiền: @Model.billproducts.Sum(n => n.unit_price * n.quantity).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br /><br />

        <input type="submit" value="Lưu đơn hàng" id="btnLuuDonHang" class="btn btn-danger" />
        
    </div>
}

WebsiteBanHang/Views/QuanLyDonHang/InDonHang.cshtml
@using WebsiteBanHang.Models;
@model Bill
<h2>Thông tin đơn hàng </h2>
<br />
<br />


    <div class="ChiTietDonHang table">
        @{ IEnumerable<billproduct> lstChiTietDH = (IEnumerable<billproduct>)ViewBag.ListChiTietDH;}

        <table class="table" id="table">
            @*Thông tin đơn hàng*@
            <tr>
                @*<td>Mã đơn hàng: <b style="color:red">@Model.Id @Html.Hidden("Id", Model.Id)</b></td>*@

                <td>Tên khách hàng: <b style="color:red">@Model.user.name</b></td>
                <td>SĐT:@Model.user.phone</td>
                @*<td>Ngày đặt: @Model.buy_date.Value.ToString("dd/MM/yyy")</td>*@
                <td>Địa chỉ: @Model.user.address</td>


            </tr>
            @*Phần chi tiết đơn hàng*@
            <tr>
                
                <td><b>Sản phẩm</b></td>
                
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>
           
            @foreach (var item in lstChiTietDH)
            {

                <tr>
                   
                    <td>@item.product.name</td>
                    
                    <td>@item.quantity</td>
                    <td>@item.unit_price</td>
                </tr>

            }


            <tr id="tt">
                <td>Tổng số lượng: @Model.billproducts.Sum(n => n.quantity)</td>
                <td>Tổng tiền: @Model.billproducts.Sum(n => n.unit_price * n.quantity).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br /><br />
    </div>
  <a href="@Url.Action("InDonHang1","QuanLyDonHang",new { id = Model.Id })">In đơn hàng</a>          

WebsiteBanHang/Views/QuanLyDonHang/xacnhan.cshtml
@using WebsiteBanHang.Models;
@model Bill

@{
    ViewBag.Title = "xacnhan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Thông tin đơn hàng <font color="red">@Model.user.name</font></h2>
<br />
<br />

@using (Html.BeginForm())
{
    <div class="ChiTietDonHang table">
        @{ IEnumerable<billproduct> lstChiTietDH = (IEnumerable<billproduct>)ViewBag.ListChiTietDH;}

        <table class="table" id="table">
            @*Thông tin đơn hàng*@
            <tr>
                <td>Mã đơn hàng: <b style="color:red">@Model.Id @Html.Hidden("Id", Model.Id)</b></td>
                <td>Mã khách hàng: <b style="color:red">@Model.user.Id</b></td>
                <td>Tên khách hàng: <b style="color:red">@Model.user.name</b></td>
                <td>Ngày đặt: @Model.buy_date.Value.ToString("dd/MM/yyy")</td>
                
            </tr>
            @*Phần chi tiết đơn hàng*@
            <tr>
                <td></td>
                <td><b>Sản phẩm</b></td>
                <td><b>Hình ảnh</b></td>
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>
            @{
                int i = 1;
            }
            @foreach (var item in lstChiTietDH)
            {

                <tr>
                    <td>@i</td>
                    <td>@item.product.name</td>
                    <td><img width="120" height="120" src="@Url.Content("~/Content/HinhAnhSP/" + @item.product.image1)" /></td>
                    <td>@item.quantity</td>
                    <td>@item.unit_price</td>
                </tr>
                { i++; }
            }


            <tr>
                <td>Tổng số lượng: @Model.billproducts.Sum(n => n.quantity)</td>
                <td>Tổng tiền: @Model.billproducts.Sum(n => n.unit_price * n.quantity).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br /><br />

        <input class="btn-danger" type="submit" value="xác nhận đơn hàng" id="btnLuuDonHang" />

    </div>
}