WebsiteBanHang/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    public class DonHangController : BaseController
    {

        QuanLyBanHang6Entities db = new QuanLyBanHang6Entities();
        // GET: DonHang
        public ActionResult DangXacNhan()
        {
            user tv = Session["TaiKhoan"] as user;
            var lst = db.Bills.Where(n => n.status == false&&n.buyer_id==tv.Id).OrderBy(n => n.buy_date);
            return View(lst);
           
        }
        public ActionResult DaXacNhan()
        {
            user tv = Session["TaiKhoan"] as user;
            var lst = db.Bills.Where(n => n.status == true && n.buyer_id == tv.Id).OrderBy(n => n.buy_date);
            return View(lst);

        }
        public ActionResult DaGiao()
        {
            user tv = Session["TaiKhoan"] as user;
            var lst = db.Bills.Where(n => n.transport_status== true&& n.buy_status == false && n.buyer_id == tv.Id).OrderBy(n => n.buy_date);
            return View(lst);

        }
        public ActionResult DaHoanThanh()
        {
            user tv = Session["TaiKhoan"] as user;
            var lst = db.Bills.Where(n => n.buy_status == true && n.buyer_id == tv.Id).OrderBy(n => n.buy_date);
            return View(lst);

        }
        [HttpGet]
        public ActionResult XemDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill model = db.Bills.SingleOrDefault(n => n.Id == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            // Lấy ds chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        public ActionResult XemDonHangHoanThanh(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill model = db.Bills.SingleOrDefault(n => n.Id == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            // Lấy ds chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.billproducts.Where(n => n.bill_id == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        [HttpPost]
        public ActionResult NhanXet(int MaSP,FormCollection f)
        {
            string nhanxet= f["txtNhanXet"].ToString();
            user tv = Session["TaiKhoan"] as user;
            comment bl = new comment();
            bl.comment1 = nhanxet;
            bl.comment_date = DateTime.Now;
            bl.commenter_id = tv.Id;
            bl.product_id = MaSP;
            db.comments.Add(bl);
            db.SaveChanges();
            SetAlert("Nhận xét sản phẩm thành công", "success");
            return RedirectToAction("DaHoanThanh");
        }
    }
}

WebsiteBanHang/Views/Layout/DanhMucDonHang.cshtml
<div class="col-md-3 single-grid1 " style="background-color: #424242;">
    <h3 style="color:white; padding:40px 0px 20px 0px;">Đơn hàng</h3>
    <div class="recent-grids ">

        <div class="recent-center">
            <br />
            <h6 class="best2"><a href="@Url.Action("DangXacNhan","DonHang")" style="color:white;padding-bottom:20px;">Đơn hàng đang xác nhận </a></h6>

        </div>
        <div class="clearfix"> </div>
    </div>

    <div class="recent-grids">
        <div class="recent-center">
            <h6 class="best2"><a href="@Url.Action("DaXacNhan","DonHang")" style="color:white;padding-bottom:20px;">Đơn hàng đã xác nhận </a></h6>

        </div>
        <div class="clearfix"> </div>
    </div>
    <div class="recent-grids">
        <div class="recent-center">
            <h6 class="best2"><a href="@Url.Action("DaGiao","DonHang")" style="color:white;padding-bottom:20px;">Đơn hàng đã giao  </a></h6>

        </div>
        <div class="clearfix"> </div>
    </div>
    <div class="recent-grids">
        <div class="recent-center">
            <h6 class="best2"><a href="@Url.Action("DaHoanThanh","DonHang")" style="color:white;padding-bottom:150px;"> Đơn hàng đã hoàn thành</a> </h6>

        </div>
        <div class="clearfix"> </div>
    </div>
</div>

WebsiteBanHang/Views/Layout/HeaderTop.cshtml
@using WebsiteBanHang.Models;
<div class="header-top">
    <div class="container">
        <div class="top-left">
            <a href="#"> Trợ giúp  <i class="glyphicon glyphicon-phone" aria-hidden="true"></i> +0123-456-789</a>
        </div>
        <div class="top-right">
            <ul>
                @*<li><a href="checkout.html">Checkout</a></li>*@
                @if (Session["TaiKhoan"] != null && Session["TaiKhoan"] != "")
                {
                    user tv = (user)Session["TaiKhoan"];
                    <li style="color:white">Chào @tv.name</li>
                    <li style="color:white">@Html.ActionLink("Đơn hàng", "DangXacNhan", "DonHang")</li>
                    <li style="color:white"> @Html.ActionLink("Đăng xuất", "DangXuat", "home")</li>
                    <li style="color:white">@Html.ActionLink("Quản trị", "Index", "QuanLySanPham")</li>
                }
                else
                {


                    <li><a href="#" onclick="openForm()" id="btnDangNhap">Đăng nhập</a></li>
                    <li>@Html.ActionLink("Đăng ký", "DangKy", "Home")</li>
                }
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="form-popup" id="myForm">
    @using (Ajax.BeginForm("DangNhap", "Home",new AjaxOptions {InsertionMode=InsertionMode.Replace,UpdateTargetId="thongbao" }))
    {

        <div action="/action_page.php" class="form-container">
            <h1>Đăng nhập</h1>

            <label for="usn"><b>Tên đăng nhập</b></label>
            <input type="text" placeholder="tên đăng nhập" name="txtTenDangNhap" required/>
            
            <label for="psw"><b>Mật khẩu</b></label>
            <input type="password" placeholder="mật khẩu" name="txtMatKhau" required/>
                <p style="font-weight:bold;color:red;text-align:left" id="thongbao">@ViewBag.thongbao1 </p>
            <button type="submit" class="btn">Đăng nhập</button>
            <button type="button" class="btn cancel" onclick="closeForm()">Đóng</button>
        </div> 
    }   
</div>
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    * {
        box-sizing: border-box;
    }
    h1{ 
        text-align:center;
    }
    /* Button used to open the contact form - fixed at the bottom of the page */
    .open-button {
        background-color: #555;
        color: white;
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        opacity: 0.8;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
    }

    /* The popup form - hidden by default */
    .form-popup {
        display: none;
        position: fixed;
        top:0;
        right: 15px;
        border: 3px solid #f1f1f1;
        z-index: 9;
    }

    /* Add styles to the form container */
    .form-container {
        max-width: 300px;
        padding: 10px;
        background-color: white;
    }

        /* Full-width input fields */
        .form-container input[type=text], .form-container input[type=password] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            border: none;
            background: #f1f1f1;
        }

            /* When the inputs get focus, do something */
            .form-container input[type=text]:focus, .form-container input[type=password]:focus {
                background-color: #ddd;
                outline: none;
            }

        /* Set a style for the submit/login button */
        .form-container .btn {
            background-color: #4CAF50;
            color: white;
            padding: 16px 20px;
            border: none;
            cursor: pointer;
            width: 100%;
            margin-bottom: 10px;
            opacity: 0.8;
        }

        /* Add a red background color to the cancel button */
        .form-container .cancel {
            background-color: red;
        }

        /* Add some hover effects to buttons */
        .form-container .btn:hover, .open-button:hover {
            opacity: 1;
        }
</style>
<script>
    function openForm() {
        document.getElementById("myForm").style.display = "block";
    }

    function closeForm() {
        document.getElementById("myForm").style.display = "none";
    }
</script>

WebsiteBanHang/Views/Layout/alert.cshtml
@if (TempData["AlertMessage"] != null)
{
    <div id="AlertBox" class="alert @TempData["AlertType"] hide">
       @TempData["AlertMessage"]
    </div>
}
<script>
    $(function () {
        $('#AlertBox').removeClass('hide');
        $('#AlertBox').delay(2000).slideUp(500);
    });
</script>